---
title: 'Final Project: Guidance Document and Checksheet'
author: "Author Name(s)"
date: "Due June 26, 2023"
output:  html_notebook
---

# Purpose

Line 19-25 in .Rmd file


# Final Project Requirements

### Data Access

(A) Line 41 & 45 in .Rmd file  


(B) Line 43 & 47 in .Rmd file 


### Data Wrangling

(A) Line 57 in .Rmd file 


(B) Line 57 in .Rmd file


(C) Line 112 in .Rmd file


### Data Visualization (3 of 5 required)

(A) Line 80 & 83 in .Rmd file  

(B) Line 89-95 in .Rmd file 

(C) Line 109-133 in .Rmd file   


### Other requirements (Nothing for you to report in this Guidance Document)

(A) *All data visualizations* must be relevant to the stated research question, and the report must include at least one effective display of many (at least 3) variables.

(B) *Code quality:* Code formatting is consistent throughout entire document. Specifically, all code chunks demonstrate proficiency with (1) meaningful object names (2) proper use of white space especially with respect to infix operators, chain operators, commas, brackets/parenthesis, etc (3) use of `<-` assignment operator throughout (4) use of meaningful comments (you must include comments in your document).

(C) *Narrative quality:* The narrative text (1) clearly states one research question that motivates the overall analysis, (2) explains reasoning for each significant step in the analysis and it's relationship to the research question, (3) explains significant findings and conclusions as they relate to the research question, and (4) is free of errors in spelling and grammar.

(D) *Overall Quality:* Submitted project shows significant effort to produce a high-quality and thoughtful analysis that showcases STAT 184 skills. (1) The project must be self-contained, such that the analysis can be entirely rerun without errors. (2) Analysis is coherent, well-organized, and free of extraneous content such as data dumps, unrelated graphs, and other content that is not overtly connected to the research question.

(E) Project is submitted as a self-contained GitHub Repo. 
